name: Docker Image CI

on:
  push:
    branches: [ "sophware-patch-1" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        #build-args
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tsbastionazure:0.1.0
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tsbastionazure:latest
